GET http://localhost:3500/student/allStudents

###
POST http://localhost:3500/student/signup
Content-Type: application/json

{
    "roll":"22071A05K5",
    "name":"Akula Sharath",
    "mail":"sharath@gmail.com",
    "batch":"VNR_2026_B1",
    "section":"CSE-4",
    "password":"sharath",
    "position" :"student"
}



###
POST http://localhost:3500/student/login
Content-Type:  application/json

{
    "roll":"21071A05K8",
    "password":"pavan"
}

### Mentor

GET http://localhost:3500/mentor/allMentors

###
POST http://localhost:3500/mentor/signup
Content-Type: application/json

{
    "roll": "22071A05K6",
    "name": "Allagundu Musher",
    "mail": "manish@gmial.com",
    "batch": "VNR_2026_B1",
    "section": "CSE-4",
    "password":"musheer",
    "position" :"mentor"
}

###
POST http://localhost:3500/mentor/login
Content-Type:  application/json

{
    "roll":"21071a05e8",
    "password":"vnrvjiet"
}

### Admin

GET http://localhost:3500/admin/allAdmins

###
POST http://localhost:3500/admin/signup
Content-Type: application/json

{
    "roll":"21071A05K8",
    "name":"Anangi Pavan",
    "mail":"pavan@gmail.com",
    "batch":"VNR_2025_B1",
    "section":"CSE-4",
    "password":"pavan@123",
    "position" :"admin"
}

###
POST http://localhost:3500/admin/login
Content-Type:  application/json

{
    "roll":"21071A05E5",
    "password":"tanaya"
}


###
GET http://localhost:3500/assignments/EntireAssignments

###
GET http://localhost:3500/assignments/AllAssignments

###
POST http://localhost:3500/submissions/assignmentSubmissions